### ISSUE TITLE
symbol not found in flat namespace '_exif_data_free'

### ISSUE THREAD

**Issue by cjavdev** [tonytonyjan/exif#33]
I was able to successfully install with:

```sh
C_INCLUDE_PATH=$(brew --prefix libexif)/include gem install exif
```

but when I try to import and use the library I get this error:

```
irb(main):001:0> require 'exif'
<internal:/Users/cjavilla/.asdf/installs/ruby/3.2.2/lib/ruby/site_ruby/3.2.0/rubygems/core_ext/kernel_require.rb>:85:in `require': dlopen(/Users/cjavilla/.asdf/installs/ruby/3.2.2/lib/ruby/gems/3.2.0/gems/exif-2.2.4/lib/exif/exif.bundle, 0x0009): symbol not found in flat namespace '_exif_data_free' - /Users/cjavilla/.asdf/installs/ruby/3.2.2/lib/ruby/gems/3.2.0/gems/exif-2.2.4/lib/exif/exif.bundle (LoadError)
	from <internal:/Users/cjavilla/.asdf/installs/ruby/3.2.2/lib/ruby/site_ruby/3.2.0/rubygems/core_ext/kernel_require.rb>:85:in `require'
	from /Users/cjavilla/.asdf/installs/ruby/3.2.2/lib/ruby/gems/3.2.0/gems/exif-2.2.4/lib/exif.rb:4:in `<top (required)>'
	from <internal:/Users/cjavilla/.asdf/installs/ruby/3.2.2/lib/ruby/site_ruby/3.2.0/rubygems/core_ext/kernel_require.rb>:159:in `require'
	from <internal:/Users/cjavilla/.asdf/installs/ruby/3.2.2/lib/ruby/site_ruby/3.2.0/rubygems/core_ext/kernel_require.rb>:159:in `rescue in require'
	from <internal:/Users/cjavilla/.asdf/installs/ruby/3.2.2/lib/ruby/site_ruby/3.2.0/rubygems/core_ext/kernel_require.rb>:39:in `require'
	from (irb):1:in `<main>'
	from /Users/cjavilla/.asdf/installs/ruby/3.2.2/lib/ruby/gems/3.2.0/gems/irb-1.7.0/exe/irb:9:in `<top (required)>'
	from /Users/cjavilla/.asdf/installs/ruby/3.2.2/bin/irb:25:in `load'
	from /Users/cjavilla/.asdf/installs/ruby/3.2.2/bin/irb:25:in `<main>'
<internal:/Users/cjavilla/.asdf/installs/ruby/3.2.2/lib/ruby/site_ruby/3.2.0/rubygems/core_ext/kernel_require.rb>:85:in `require': cannot load such file -- exif (LoadError)
	from <internal:/Users/cjavilla/.asdf/installs/ruby/3.2.2/lib/ruby/site_ruby/3.2.0/rubygems/core_ext/kernel_require.rb>:85:in `require'
	from (irb):1:in `<main>'
	from /Users/cjavilla/.asdf/installs/ruby/3.2.2/lib/ruby/gems/3.2.0/gems/irb-1.7.0/exe/irb:9:in `<top (required)>'
	from /Users/cjavilla/.asdf/installs/ruby/3.2.2/bin/irb:25:in `load'
	from /Users/cjavilla/.asdf/installs/ruby/3.2.2/bin/irb:25:in `<main>'
```

I'm using Apple silicon locally (Apple M2 Max)

I also tried cloning this repo and running the load_file benchmark:

```
ruby load_file.rb
<internal:/Users/cjavilla/.asdf/installs/ruby/3.2.2/lib/ruby/site_ruby/3.2.0/rubygems/core_ext/kernel_require.rb>:37:in `require': cannot load such file -- exif/exif (LoadError)
	from <internal:/Users/cjavilla/.asdf/installs/ruby/3.2.2/lib/ruby/site_ruby/3.2.0/rubygems/core_ext/kernel_require.rb>:37:in `require'
	from /Users/cjavilla/repos/exif/lib/exif.rb:4:in `<top (required)>'
	from <internal:/Users/cjavilla/.asdf/installs/ruby/3.2.2/lib/ruby/site_ruby/3.2.0/rubygems/core_ext/kernel_require.rb>:37:in `require'
	from <internal:/Users/cjavilla/.asdf/installs/ruby/3.2.2/lib/ruby/site_ruby/3.2.0/rubygems/core_ext/kernel_require.rb>:37:in `require'
	from /Users/cjavilla/repos/exif/benchmark/env.rb:10:in `<top (required)>'
	from <internal:/Users/cjavilla/.asdf/installs/ruby/3.2.2/lib/ruby/site_ruby/3.2.0/rubygems/core_ext/kernel_require.rb>:85:in `require'
	from <internal:/Users/cjavilla/.asdf/installs/ruby/3.2.2/lib/ruby/site_ruby/3.2.0/rubygems/core_ext/kernel_require.rb>:85:in `require'
	from load_file.rb:3:in `<main>'
```

Any ideas?

**Comment by cjavdev** [comment]
```
brew info libexif
==> libexif: stable 0.6.24 (bottled)
EXIF parsing library
https://libexif.github.io/
/opt/homebrew/Cellar/libexif/0.6.24 (59 files, 3.1MB) *
  Poured from bottle using the formulae.brew.sh API on 2023-05-01 at 08:04:12
From: https://github.com/Homebrew/homebrew-core/blob/HEAD/Formula/libexif.rb
License: LGPL-2.1
==> Dependencies
Build: autoconf ✔, automake ✔, libtool ✔
Required: gettext ✔
==> Analytics
install: 81,305 (30 days), 81,305 (90 days), 81,305 (365 days)
install-on-request: 0 (30 days), 0 (90 days), 0 (365 days)
build-error: 0 (30 days)
```

**Comment by cjavdev** [comment]
```
asdf --version

v0.11.3
ruby --version
ruby 3.2.2 (2023-03-30 revision e51014f9c0) [arm64-darwin22]
clang --version
Apple clang version 14.0.3 (clang-1403.0.22.14.1)
Target: arm64-apple-darwin22.4.0
Thread model: posix
InstalledDir: /Library/Developer/CommandLineTools/usr/bin
```

**Comment by yboulkaid** [comment]
I ran into this too, to build the native extension I had to specify both the include flag and the LDFLAGS:

```
gem install exif -- --with-cflags="-I$(brew --prefix libexif)/include" --with-ldflags="-L$(brew --prefix libexif)/lib"
```
